AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
  
Resources:

  SAMLogs:  
    Type: AWS::Logs::LogGroup

  OrderStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: EXPRESS
      DefinitionUri: order.asl.json
      DefinitionSubstitutions:
        MakePaymentFunctionArn: !GetAtt MakePaymentFunction.Arn
        MakeOrderFunctionArn: !GetAtt MakeOrderFunction.Arn
        OrderFailureFunctionArn: !GetAtt OrderFailureFunction.Arn
      Events:
        OrderApiEvent:
          Type: Api
          Properties:
            Method: post
            Path: /order
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt SAMLogs.Arn
        IncludeExecutionData: true
        Level: ALL
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref MakePaymentFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref MakeOrderFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref OrderFailureFunction
        - CloudWatchLogsFullAccess
  
  MakePaymentFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ./makePaymentFunction
      Handler: payment.handler
      Runtime: nodejs12.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdersTable
      Environment:
        Variables:
          ORDERS_TABLE: !Ref OrdersTable

  MakeOrderFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ./makeOrderFunction
      Handler: order.handler
      Runtime: nodejs12.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdersTable
      Environment:
        Variables:
          ORDERS_TABLE: !Ref OrdersTable    

  OrderFailureFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ./orderFailureFunction
      Handler: orderFailure.handler
      Runtime: nodejs12.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdersTable
      Environment:
        Variables:
          ORDERS_TABLE: !Ref OrdersTable

  OrdersTable:
    Type: AWS::Serverless::SimpleTable
  

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  OrderApi:
    Description: "API Gateway endpoint URL for Prod stage for Order function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/order/"
