AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
  
Resources:
  MakePaymentFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ./makePaymentFunction
      Handler: payment.handler
      Runtime: nodejs12.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdersTable
        - SQSSendMessagePolicy:
            QueueName: !GetAtt OrdersQueue.QueueName
      Environment:
        Variables:
          ORDERS_TABLE: !Ref OrdersTable
          ORDERS_QUEUE_URL: !Ref OrdersQueue
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /order
            Method: post

  MakeOrderFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ./makeOrderFunction
      Handler: order.handler
      Runtime: nodejs12.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdersTable
      Environment:
        Variables:
          ORDERS_TABLE: !Ref OrdersTable    
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt OrdersQueue.Arn 
  

  OrdersTable:
    Type: AWS::Serverless::SimpleTable
  
  OrdersQueue:
    Type: AWS::SQS::Queue

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  OrderApi:
    Description: "API Gateway endpoint URL for Prod stage for Order function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/order/"
